name: ART4ALL - SERGIOJARAMILLO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60992
title: ART 4 ALL - SERGIO JARAMILLO A.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#455568'
    - '#130f0c'
    - '#e7d4ad'
    - '#bb996f'
    - '#9b3d2a'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
