name: ART4ALL - SERGIOJARAMILLO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60992
title: ART 4 ALL - SERGIO JARAMILLO A.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#455568'
    - '#130f0c'
    - '#e7d4ad'
    - '#bb996f'
    - '#9b3d2a'
  brandStrength: 0.20239130686968565
  lightness: 0.07687950995750725
  saturation: 0.7710077497176826
  rhythmicContrast: 0.4330489323474467
purpose: []
