title: 'ART 4 ALL '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#455568'
    - '#130f0c'
    - '#e7d4ad'
    - '#bb996f'
    - '#9b3d2a'
  lightness: 0.1875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'ART 4 ALL '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6015
layout_spectrum: 0.3942652
