name: 'ART 4 ALL '
favicon: null
layout_spectrum: 0.21158
typography_spectrum: 0.6015
title: ARTISTA - SERGIO JARAMILLO AGUIRREZABAL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#455568'
    - '#130f0c'
    - '#e7d4ad'
    - '#bb996f'
    - '#9b3d2a'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
